### ISSUE TITLE
[Feature Request] Support for build flavor

### ISSUE THREAD

**Issue by Jawnnypoo** [Stuie/papercut#3]
This is very similar to #1 but I think it would be great if the build were to fail if you were to be in the release build flavor of the Android build, but would otherwise be fine on debug builds. 

You could achieve it in a similar way to [LeakCanary](https://github.com/square/leakcanary/blob/master/leakcanary-android-no-op/src/main/java/com/squareup/leakcanary/LeakCanary.java) where the user could have a `debugCompile` which uses the no-op version of the library, and `releaseCompile` where it uses the normal version of the library.

**Comment by gaara87** [comment]
+1

**Comment by Stuie** [comment]
I believe the configuration below would achieve the desired result.

```groovy
dependencies {
    releaseAnnotationProcessor: 'ie.stu:papercut-compiler:0.0.2'
    compile: 'ie.stu:papercut-annotations:0.0.2'
}
```

The annotations don't do anything by themselves, and the compiler would only execute on release builds.

LeakCanary needs a no-op implementation because of the `LeakCanary.install();` line. There's no such line for Papercut.

I'll close the issue for now, but please re-open if that's not working for you. :)

**Comment by Jawnnypoo** [comment]
Nice! I think this would be a great thing to add to the README for others who may not realize this configuration. Would you like me to make a PR?

**Comment by Stuie** [comment]
Sure. I'll probably merge it in along with some other changes either today or tomorrow. Just have to do a bunch of testing.
